### PR TITLE
Move Go files into src directory

### PR DESCRIPTION
**Pull request by AlexisDeschamps**
Issue: https://github.com/dxe/alc-mobile-api/issues/16

## Testing
See that the output is as expected for:
Run `make dev`
Run `make test`

### CODE REVIEW

**Comment by AlexisDeschamps** [comment]
@jakehobbs It loos like this works out of the box. Do you know if there is an expected way it could break?

**Comment by jakehobbs** [comment]
The dev Dockerfile also needs to be updated with new path: ```go build -o alc-mobile-api ./src```, then I think this should be fine.

I think the problem I was running into before was just that I was also trying to move the templates, static, and model directories into src. But maybe that is not something we want to do.

**Review by jakehobbs — CHANGES_REQUESTED** [review]
The dev Dockerfile also needs to be updated with new path: go build -o alc-mobile-api ./src, then I think this should be fine.

I think the problem I was running into before was just that I was also trying to move the templates, static, and model directories into src. But maybe that is not something we want to do.

**Comment by AlexisDeschamps** [comment]
@jakehobbs Cool, thanks. I tried to also do that and made some other updates Does `Dockerfile-prod` not also need to be changed?

Tests I ran:
- `make dev`: output looked the same as the `main` branch
- `make test`: output looked the same as the `main` branch
- `docker build -f Dockerfile -t dev-test .`: output is `stderr: 2021/09/13 00:26:13 missing configuration for DB_DSN` so it seems to work
- `docker build -f Dockerfile-prod -t prod-test .`: output is `stderr: 2021/09/13 00:26:13 missing configuration for DB_DSN` so it seems to work

**Comment by jakehobbs** [comment]
Everything seems to be working for me locally with a full config. Do we want the ```model``` directory to be inside of the ```main``` directory though? It feels a bit weird to me, but I'm not sure what the standard practice is.

**Pull request closed without merging**
